#!/usr/bin/env python3
"""Inspect AMP_TK and sim2sim_pi_plus.py for pi_plus migration facts."""

from __future__ import annotations

import ast
import re
from collections import defaultdict
from pathlib import Path

KEYWORDS = [
    "joint_names",
    "default_joint",
    "default_dof",
    "kp",
    "kd",
    "stiffness",
    "damping",
    "action_scale",
    "control_dt",
    "sim_dt",
    "foot",
    "ankle",
    "hip",
    "knee",
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def main() -> None:
    root = repo_root()
    amp_dir = (root / "../AMP_TK").resolve()
    sim2sim = (root / "../sim2sim_pi_plus.py").resolve()
    report_path = root / "reports/pi_plus_asset_report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("# pi_plus AMP_TK Asset Report\n")
    lines.append("Generated by `scripts/inspect_amp_tk.py`.\n")

    lines.extend(directory_summary(amp_dir))
    lines.extend(file_findings(amp_dir))
    lines.extend(keyword_findings(amp_dir, sim2sim))
    lines.extend(sim2sim_findings(sim2sim))

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {report_path}")


def directory_summary(amp_dir: Path) -> list[str]:
    lines = ["## AMP_TK Directory Tree Summary", ""]
    if not amp_dir.exists():
        return lines + [f"TODO: AMP_TK not found at `{amp_dir}`.", ""]

    max_depth = 3
    for path in sorted(amp_dir.rglob("*")):
        rel = path.relative_to(amp_dir)
        if len(rel.parts) > max_depth:
            continue
        suffix = "/" if path.is_dir() else ""
        lines.append(f"- `{rel}{suffix}`")
    lines.append("")
    return lines


def file_findings(amp_dir: Path) -> list[str]:
    all_files = [p for p in amp_dir.rglob("*") if p.is_file()] if amp_dir.exists() else []
    pi_plus_files = [p for p in all_files if "pi_plus" in str(p).lower()]
    asset_files = [p for p in all_files if p.suffix.lower() in {".urdf", ".xml", ".mjcf"}]
    mesh_files = [p for p in all_files if p.suffix.lower() in {".stl", ".obj", ".dae", ".ply"}]

    lines = ["## Files Containing pi_plus", ""]
    lines.extend(format_paths(pi_plus_files, amp_dir))
    lines.extend(["", "## URDF/MJCF/XML Files", ""])
    lines.extend(format_paths(asset_files, amp_dir))
    lines.extend(["", "## Mesh Files", ""])
    lines.extend(format_paths(mesh_files, amp_dir))
    lines.append("")
    return lines


def keyword_findings(amp_dir: Path, sim2sim: Path) -> list[str]:
    files = []
    if amp_dir.exists():
        files.extend(p for p in amp_dir.rglob("*.py") if p.is_file())
        files.extend(p for p in amp_dir.rglob("*.yaml") if p.is_file())
        files.extend(p for p in amp_dir.rglob("*.xml") if p.is_file())
        files.extend(p for p in amp_dir.rglob("*.urdf") if p.is_file())
    if sim2sim.exists():
        files.append(sim2sim)

    hits: dict[str, list[str]] = defaultdict(list)
    for path in files:
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for lineno, line in enumerate(text.splitlines(), 1):
            low = line.lower()
            for keyword in KEYWORDS:
                if keyword.lower() in low:
                    rel = path.relative_to(repo_root().parent) if path.is_absolute() else path
                    hits[keyword].append(f"- `{rel}:{lineno}`: `{line.strip()[:180]}`")

    lines = ["## Keyword Hits", ""]
    for keyword in KEYWORDS:
        lines.append(f"### `{keyword}`")
        if hits[keyword]:
            lines.extend(hits[keyword][:40])
            if len(hits[keyword]) > 40:
                lines.append(f"- ... {len(hits[keyword]) - 40} more hits omitted")
        else:
            lines.append("- TODO: no automatic hit found.")
        lines.append("")
    return lines


def sim2sim_findings(sim2sim: Path) -> list[str]:
    lines = ["## sim2sim_pi_plus.py Extracted Facts", ""]
    if not sim2sim.exists():
        return lines + [f"TODO: `{sim2sim}` not found.", ""]

    text = sim2sim.read_text(encoding="utf-8", errors="ignore")
    tree = ast.parse(text)
    assignments = collect_assignments(tree)

    parser_default = re.search(r'--model".*?default=os\.path\.join\((.*?)\)', text, flags=re.S)
    model_hint = "TODO: could not determine model path automatically."
    if parser_default:
        model_hint = "Default parser model joins LEGGED_LAB_ROOT_DIR with `legged_lab/assets/hightorque/pi_plus/pi_plus.xml`."

    lines.append(f"- model path: {model_hint}")
    lines.append("- policy path: TODO: argparse default is null; user supplies policy externally.")
    lines.append(f"- action scale: `{extract_class_attr(tree, 'SimToSimCfg', 'sim', 'action_scale') or 'TODO'}`")
    dt = extract_class_attr(tree, "SimToSimCfg", "sim", "dt")
    decimation = extract_class_attr(tree, "SimToSimCfg", "sim", "decimation")
    lines.append(f"- sim dt: `{dt or 'TODO'}`")
    if dt is not None and decimation is not None:
        lines.append(f"- control frequency: control_dt = dt * decimation = `{float(dt) * float(decimation):.6g}` s")
    else:
        lines.append("- control frequency: TODO")

    for name in ["default_dof_pos", "kps", "kds", "isaac_to_mujoco_idx", "mujoco_to_isaac_idx"]:
        value = assignments.get(name)
        lines.append(f"- {name}: `{value if value is not None else 'TODO'}`")

    lines.extend(
        [
            "",
            "### Joint Order",
            "",
            "MuJoCo action joint order is documented in comments in `sim2sim_pi_plus.py` near `init_variables`.",
            "TODO: verify Genesis reports the same order after asset load.",
            "",
            "### Observation Layout",
            "",
            "- `obs[0:3]`: angular velocity",
            "- `obs[3:6]`: projected gravity",
            "- `obs[6:9]`: command velocity",
            "- `obs[9:29]`: joint positions minus defaults, remapped to Isaac order",
            "- `obs[29:49]`: joint velocities, remapped to Isaac order",
            "- `obs[49:69]`: previous action",
            "- history length: `5`; per-step observation size: `69`",
            "",
            "### PD Control Logic",
            "",
            "- `target_dof_pos = action * action_scale + default_dof_pos` after `isaac_to_mujoco_idx` remap.",
            "- torque command: `(target_q - q) * kp + (target_dq - dq) * kd` with zero target velocity.",
            "- TODO: map this to Genesis joint target/torque API after load validation.",
            "",
        ]
    )
    return lines


def collect_assignments(tree: ast.AST) -> dict[str, object]:
    values: dict[str, object] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name) and target.value.id == "self":
                    if target.attr in {"default_dof_pos", "kps", "kds", "isaac_to_mujoco_idx", "mujoco_to_isaac_idx"}:
                        values[target.attr] = safe_literal(node.value)
    return values


def extract_class_attr(tree: ast.AST, outer: str, inner: str, attr: str):
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == outer:
            for child in node.body:
                if isinstance(child, ast.ClassDef) and child.name == inner:
                    for stmt in child.body:
                        if isinstance(stmt, ast.Assign):
                            for target in stmt.targets:
                                if isinstance(target, ast.Name) and target.id == attr:
                                    return safe_literal(stmt.value)
    return None


def safe_literal(node: ast.AST):
    try:
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "array":
            return ast.literal_eval(node.args[0])
        return ast.literal_eval(node)
    except Exception:
        return "TODO: could not literal-evaluate expression"


def format_paths(paths: list[Path], base: Path) -> list[str]:
    if not paths:
        return ["- TODO: no files found."]
    return [f"- `{p.relative_to(base)}`" for p in sorted(paths)[:200]]


if __name__ == "__main__":
    main()
